/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ethereum Plugin
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email: support@kevlar.xyz
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GettheconfigurationRequest {
    accept: any;
    xVAULTREQUEST: any;
    xVAULTTOKEN: any;
}

export interface WriteaconfigurationRequest {
    accept: any;
    xVAULTREQUEST: any;
    xVAULTTOKEN: any;
    body: any | null;
}

/**
 * 
 */
export class ConfigApi extends runtime.BaseAPI {

    /**
     * get the configuration
     */
    async gettheconfigurationRaw(requestParameters: GettheconfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.accept === null || requestParameters.accept === undefined) {
            throw new runtime.RequiredError('accept','Required parameter requestParameters.accept was null or undefined when calling gettheconfiguration.');
        }

        if (requestParameters.xVAULTREQUEST === null || requestParameters.xVAULTREQUEST === undefined) {
            throw new runtime.RequiredError('xVAULTREQUEST','Required parameter requestParameters.xVAULTREQUEST was null or undefined when calling gettheconfiguration.');
        }

        if (requestParameters.xVAULTTOKEN === null || requestParameters.xVAULTTOKEN === undefined) {
            throw new runtime.RequiredError('xVAULTTOKEN','Required parameter requestParameters.xVAULTTOKEN was null or undefined when calling gettheconfiguration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.accept !== undefined && requestParameters.accept !== null) {
            headerParameters['Accept'] = String(requestParameters.accept);
        }

        if (requestParameters.xVAULTREQUEST !== undefined && requestParameters.xVAULTREQUEST !== null) {
            headerParameters['X-VAULT_REQUEST'] = String(requestParameters.xVAULTREQUEST);
        }

        if (requestParameters.xVAULTTOKEN !== undefined && requestParameters.xVAULTTOKEN !== null) {
            headerParameters['X-VAULT-TOKEN'] = String(requestParameters.xVAULTTOKEN);
        }

        const response = await this.request({
            path: `/config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * get the configuration
     */
    async gettheconfiguration(requestParameters: GettheconfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gettheconfigurationRaw(requestParameters, initOverrides);
    }

    /**
     * write a configuration
     */
    async writeaconfigurationRaw(requestParameters: WriteaconfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.accept === null || requestParameters.accept === undefined) {
            throw new runtime.RequiredError('accept','Required parameter requestParameters.accept was null or undefined when calling writeaconfiguration.');
        }

        if (requestParameters.xVAULTREQUEST === null || requestParameters.xVAULTREQUEST === undefined) {
            throw new runtime.RequiredError('xVAULTREQUEST','Required parameter requestParameters.xVAULTREQUEST was null or undefined when calling writeaconfiguration.');
        }

        if (requestParameters.xVAULTTOKEN === null || requestParameters.xVAULTTOKEN === undefined) {
            throw new runtime.RequiredError('xVAULTTOKEN','Required parameter requestParameters.xVAULTTOKEN was null or undefined when calling writeaconfiguration.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling writeaconfiguration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.accept !== undefined && requestParameters.accept !== null) {
            headerParameters['Accept'] = String(requestParameters.accept);
        }

        if (requestParameters.xVAULTREQUEST !== undefined && requestParameters.xVAULTREQUEST !== null) {
            headerParameters['X-VAULT_REQUEST'] = String(requestParameters.xVAULTREQUEST);
        }

        if (requestParameters.xVAULTTOKEN !== undefined && requestParameters.xVAULTTOKEN !== null) {
            headerParameters['X-VAULT-TOKEN'] = String(requestParameters.xVAULTTOKEN);
        }

        const response = await this.request({
            path: `/config`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * write a configuration
     */
    async writeaconfiguration(requestParameters: WriteaconfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.writeaconfigurationRaw(requestParameters, initOverrides);
    }

}
