/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ethereum Plugin
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email: support@kevlar.xyz
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Createanaccountrequest
 */
export interface Createanaccountrequest {
    /**
     * 
     * @type {any}
     * @memberof Createanaccountrequest
     */
    inclusions: any | null;
    /**
     * 
     * @type {any}
     * @memberof Createanaccountrequest
     */
    exclusions: any | null;
}

/**
 * Check if a given object implements the Createanaccountrequest interface.
 */
export function instanceOfCreateanaccountrequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "inclusions" in value;
    isInstance = isInstance && "exclusions" in value;

    return isInstance;
}

export function CreateanaccountrequestFromJSON(json: any): Createanaccountrequest {
    return CreateanaccountrequestFromJSONTyped(json, false);
}

export function CreateanaccountrequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Createanaccountrequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inclusions': json['inclusions'],
        'exclusions': json['exclusions'],
    };
}

export function CreateanaccountrequestToJSON(value?: Createanaccountrequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inclusions': value.inclusions,
        'exclusions': value.exclusions,
    };
}

