/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ethereum Plugin
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email: support@kevlar.xyz
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Signamessagerequest
 */
export interface Signamessagerequest {
    /**
     * 
     * @type {any}
     * @memberof Signamessagerequest
     */
    message: any | null;
}

/**
 * Check if a given object implements the Signamessagerequest interface.
 */
export function instanceOfSignamessagerequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function SignamessagerequestFromJSON(json: any): Signamessagerequest {
    return SignamessagerequestFromJSONTyped(json, false);
}

export function SignamessagerequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Signamessagerequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SignamessagerequestToJSON(value?: Signamessagerequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

