/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ethereum Plugin
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email: support@kevlar.xyz
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferETHRequestModel
 */
export interface TransferETHRequestModel {
    /**
     * 
     * @type {any}
     * @memberof TransferETHRequestModel
     */
    amount: any | null;
    /**
     * 
     * @type {any}
     * @memberof TransferETHRequestModel
     */
    to: any | null;
}

/**
 * Check if a given object implements the TransferETHRequest interface.
 */
export function instanceOfTransferETHRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "to" in value;

    return isInstance;
}

export function TransferETHRequestFromJSON(json: any): TransferETHRequestModel {
    return TransferETHRequestFromJSONTyped(json, false);
}

export function TransferETHRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferETHRequestModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'to': json['to'],
    };
}

export function TransferETHRequestToJSON(value?: TransferETHRequestModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'to': value.to,
    };
}

