/* tslint:disable */
/* eslint-disable */
/**
 * Vault Ethereum Plugin
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email: support@kevlar.xyz
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Writeaconfigurationrequest
 */
export interface Writeaconfigurationrequest {
    /**
     * 
     * @type {any}
     * @memberof Writeaconfigurationrequest
     */
    chainId: any | null;
    /**
     * 
     * @type {any}
     * @memberof Writeaconfigurationrequest
     */
    rpcUrl: any | null;
}

/**
 * Check if a given object implements the Writeaconfigurationrequest interface.
 */
export function instanceOfWriteaconfigurationrequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chainId" in value;
    isInstance = isInstance && "rpcUrl" in value;

    return isInstance;
}

export function WriteaconfigurationrequestFromJSON(json: any): Writeaconfigurationrequest {
    return WriteaconfigurationrequestFromJSONTyped(json, false);
}

export function WriteaconfigurationrequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Writeaconfigurationrequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainId': json['chain_id'],
        'rpcUrl': json['rpc_url'],
    };
}

export function WriteaconfigurationrequestToJSON(value?: Writeaconfigurationrequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain_id': value.chainId,
        'rpc_url': value.rpcUrl,
    };
}

